/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import model.Car;
import model.Stavba;

/**
 *
 * @author Jožko
 */
public class CarView extends javax.swing.JPanel {
    
    private Car car;
    
    public CarView() {
        initComponents();
        
    }

    /**
     * Creates new form CarView
     *
     * @param car
     */
    public void setCar(Car car) {
        this.car = car;
        lblName.setText(car.getTyp());        
        lblUsek.setText(String.valueOf(car.getUsek()));
        lblNaloz.setText(String.valueOf(car.getNalozene()));
        lblObjem.setText(String.valueOf(car.getObjem()));
        lblRychlost.setText(String.valueOf(car.getRychlost()));
        lblAktStav.setText("0");
        prgStav.setValue(0);
    }
    
    public void setCar(double aktCas) {
        double val = car.getAktStav(aktCas);
        lblName.setText(car.getTyp());        
        lblUsek.setText(String.valueOf(car.getUsek()));
        lblNaloz.setText(String.valueOf(car.getNalozene()));
        lblObjem.setText(String.valueOf(car.getObjem()));
        lblRychlost.setText(String.valueOf(car.getRychlost()));
        lblAktStav.setText(String.valueOf(val));
        prgStav.setValue((int) val);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        prgStav = new javax.swing.JProgressBar();
        lbla56 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblAktStav = new javax.swing.JLabel();
        lblUsek = new javax.swing.JLabel();
        lblObjem = new javax.swing.JLabel();
        lblNaloz = new javax.swing.JLabel();
        lblRychlost = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblName.setText("A1");

        lbla56.setText("Úsek");

        jLabel2.setText("Objem");

        jLabel4.setText("Naložené");

        jLabel6.setText("Rýchlost");

        lblAktStav.setText("0");

        lblUsek.setText("jLabel1");

        lblObjem.setText("jLabel1");

        lblNaloz.setText("jLabel1");

        lblRychlost.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(prgStav, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(lblRychlost))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbla56)
                                    .addComponent(jLabel2))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblObjem)
                                    .addComponent(lblUsek)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(lblNaloz))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lblName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(lblAktStav)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbla56)
                    .addComponent(lblUsek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblObjem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblNaloz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblRychlost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prgStav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAktStav))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblAktStav;
    private javax.swing.JLabel lblNaloz;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblObjem;
    private javax.swing.JLabel lblRychlost;
    private javax.swing.JLabel lblUsek;
    private javax.swing.JLabel lbla56;
    private javax.swing.JProgressBar prgStav;
    // End of variables declaration//GEN-END:variables
}
